### ISSUE TITLE
Input Component Improvments

### ISSUE THREAD

**Issue by kulkarnisaumitra98** [react-dev-community/utility-components#8]
- [x] Create ref in useInput and pass it to inputProps
-> Should be able to access ref related attributes, eg. ref.current.isFocused()
- [ ] Add labelProps and customMsgProps
-> Accomodate Label and CustomMsg Components in Theme
- [x] Add variant support in Input
- [x] Way to pass props to TextInput 
-> Right now we are only able to pass secureTextInput to Input
- [x] Combine isValid and value into single state

**Comment by kulkarnisaumitra98** [comment]
Should we add validation function to theme props? What do you guys think?

**Comment by anishkoulgi** [comment]
I think theme should be only related to UI right? And the validation functions might be different for various input fields.

**Comment by kulkarnisaumitra98** [comment]
Agree, it will lead to lot of variants, cool, lets drop this thought.
